// GENERATED — DO NOT EDIT. Source: spec/components/action-button.spec.json

import { useRef } from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { expect, userEvent, waitFor, within } from "storybook/test";
import { ActionButton, type ActionButtonHandle } from "../../../packages/ui/src/actionButton/actionButton";

/**
 * One story per state reachable from "idle" (BFS over the spec's
 * transitions), plus one story that walks as much of the graph as a single
 * continuous interaction can cover. Regenerate with `pnpm generate` after
 * editing the spec — do not edit this file by hand.
 */
function ActionButtonStory(props: { settleMode?: "resolve" | "reject" | "never"; disabled?: boolean; successDuration?: number }) {
  const ref = useRef<ActionButtonHandle>(null);
  return (
    <ActionButton
      ref={ref}
      disabled={props.disabled}
      successDuration={props.successDuration ?? 300}
      onStateChange={(state) => {
        if (state === "pending" && props.settleMode !== "never") {
          const settle = props.settleMode === "reject" ? Promise.reject(new globalThis.Error("story error")) : Promise.resolve();
          settle.then(
            () => ref.current?.send({ type: "RESOLVE" }),
            () => ref.current?.send({ type: "REJECT" }),
          );
        }
      }}
    >
      Save
    </ActionButton>
  );
}

const meta: Meta<typeof ActionButtonStory> = {
  title: "Generated/ActionButton",
  component: ActionButtonStory,
};

export default meta;
type Story = StoryObj<typeof ActionButtonStory>;

export const Idle: Story = {};

export const Pending: Story = {
  args: { settleMode: "never" },
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    const button = canvas.getByRole("button");
    button.focus();
    await userEvent.keyboard("{Enter}");
    await waitFor(() => expect(button).toHaveAttribute("data-state", "pending"));
  },
};

// "disabled" has no play-function path (its transition isn't driven by click or a11y.keyboard) — reached via a construction prop instead, matching context field "disabled".
export const Disabled: Story = {
  args: { disabled: true },
};

export const Success: Story = {
  args: { settleMode: "resolve" },
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    const button = canvas.getByRole("button");
    button.focus();
    await userEvent.keyboard("{Enter}");
    // (event fires when the pending onAction settles — see the wrapper's resolveNext flag)
    await waitFor(() => expect(button).toHaveAttribute("data-state", "success"));
  },
};

export const Error: Story = {
  args: { settleMode: "reject" },
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    const button = canvas.getByRole("button");
    button.focus();
    await userEvent.keyboard("{Enter}");
    // (event fires when the pending onAction settles — see the wrapper's resolveNext flag)
    await waitFor(() => expect(button).toHaveAttribute("data-state", "error"));
  },
};

export const Retrying: Story = {
  args: { settleMode: "reject" },
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    const button = canvas.getByRole("button");
    button.focus();
    await userEvent.keyboard("{Enter}");
    // (event fires when the pending onAction settles — see the wrapper's resolveNext flag)
    button.focus();
    await userEvent.keyboard("{Enter}");
    await waitFor(() => expect(button).toHaveAttribute("data-state", "retrying"));
  },
};

/** Walks idle -> pending -> success -> idle -> pending -> error -> idle in one continuous interaction. */
export const FullGraphWalk: Story = {
  render: () => {
    const ref = useRef<ActionButtonHandle>(null);
    let calls = 0;
    return (
      <ActionButton
        ref={ref}
        successDuration={300}
        onStateChange={(state) => {
          if (state === "pending") {
            calls += 1;
            const settle = calls === 1 ? Promise.resolve() : Promise.reject(new globalThis.Error("story error"));
            settle.then(
              () => ref.current?.send({ type: "RESOLVE" }),
              () => ref.current?.send({ type: "REJECT" }),
            );
          }
        }}
      >
        Save
      </ActionButton>
    );
  },
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    const button = canvas.getByRole("button");

    await expect(button).toHaveAttribute("data-state", "idle");
    await userEvent.click(button);
    await waitFor(() => expect(button).toHaveAttribute("data-state", "success"));
    await waitFor(() => expect(button).toHaveAttribute("data-state", "idle"), { timeout: 2000 });

    await userEvent.click(button);
    await waitFor(() => expect(button).toHaveAttribute("data-state", "error"));
    button.focus();
    await userEvent.keyboard("{Escape}");
    await waitFor(() => expect(button).toHaveAttribute("data-state", "idle"));
  },
};
