// GENERATED — DO NOT EDIT. Source: spec/components/counter.spec.json

import { useRef } from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { expect, userEvent, waitFor, within } from "storybook/test";
import { Counter, type CounterHandle } from "../../../packages/ui/src/counter/counter";

/**
 * One story per state reachable from "active" (BFS over the spec's
 * transitions), plus one story that walks as much of the graph as a single
 * continuous interaction can cover. Regenerate with `pnpm generate` after
 * editing the spec — do not edit this file by hand.
 */
function CounterStory(props: { count?: number }) {
  const ref = useRef<CounterHandle>(null);
  return (
    <Counter
      ref={ref}
      count={props.count}
      decrement={"Decrement content"}
      increment={"Increment content"}
    />
  );
}

const meta: Meta<typeof CounterStory> = {
  title: "Generated/Counter",
  component: CounterStory,
};

export default meta;
type Story = StoryObj<typeof CounterStory>;

export const Active: Story = {};
