// GENERATED — DO NOT EDIT. Source: spec/components/input-tags.spec.json

import { useRef } from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { expect, userEvent, waitFor, within } from "storybook/test";
import { InputTags, type InputTagsHandle } from "../../../packages/ui/src/inputTags/inputTags";

/**
 * One story per state reachable from "active" (BFS over the spec's
 * transitions), plus one story that walks as much of the graph as a single
 * continuous interaction can cover. Regenerate with `pnpm generate` after
 * editing the spec — do not edit this file by hand.
 */
function InputTagsStory(props: { tags?: string[] }) {
  const ref = useRef<InputTagsHandle>(null);
  return (
    <InputTags
      ref={ref}
      tags={props.tags}
    />
  );
}

const meta: Meta<typeof InputTagsStory> = {
  title: "Generated/InputTags",
  component: InputTagsStory,
};

export default meta;
type Story = StoryObj<typeof InputTagsStory>;

export const Active: Story = {};
