// GENERATED — DO NOT EDIT. Source: spec/components/notification-button.spec.json

import { useRef } from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { expect, userEvent, waitFor, within } from "storybook/test";
import { NotificationButton, type NotificationButtonHandle } from "../../../packages/ui/src/notificationButton/notificationButton";

/**
 * One story per state reachable from "default" (BFS over the spec's
 * transitions), plus one story that walks as much of the graph as a single
 * continuous interaction can cover. Regenerate with `pnpm generate` after
 * editing the spec — do not edit this file by hand.
 */
function NotificationButtonStory(props: {  }) {
  const ref = useRef<NotificationButtonHandle>(null);
  return (
    <NotificationButton
      ref={ref}
      label={"Label content"}
    />
  );
}

const meta: Meta<typeof NotificationButtonStory> = {
  title: "Generated/NotificationButton",
  component: NotificationButtonStory,
};

export default meta;
type Story = StoryObj<typeof NotificationButtonStory>;

export const Default: Story = {};

export const Active: Story = {
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    const button = canvas.getByRole("button");
    button.focus();
    await userEvent.keyboard("{Enter}");
    await waitFor(() => expect(button).toHaveAttribute("data-state", "active"));
  },
};
