// GENERATED — DO NOT EDIT. Source: spec/components/status-chip.spec.json

import { useRef } from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { expect, userEvent, waitFor, within } from "storybook/test";
import { StatusChip, type StatusChipHandle } from "../../../packages/ui/src/statusChip/statusChip";

/**
 * One story per state reachable from "default" (BFS over the spec's
 * transitions), plus one story that walks as much of the graph as a single
 * continuous interaction can cover. Regenerate with `pnpm generate` after
 * editing the spec — do not edit this file by hand.
 */
function StatusChipStory(props: {  }) {
  const ref = useRef<StatusChipHandle>(null);
  return (
    <StatusChip
      ref={ref}
      content={"Content content"}
    />
  );
}

const meta: Meta<typeof StatusChipStory> = {
  title: "Generated/StatusChip",
  component: StatusChipStory,
};

export default meta;
type Story = StoryObj<typeof StatusChipStory>;

export const Default: Story = {};

// "highlighted" is reachable per the spec's transition graph but this generator found no click/keyboard/prop path to it automatically.
export const Highlighted: Story = {};
