// GENERATED — DO NOT EDIT. Source: spec/components/tag.spec.json

import { useRef } from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { expect, userEvent, waitFor, within } from "storybook/test";
import { Tag, type TagHandle } from "../../../packages/ui/src/tag/tag";

/**
 * One story per state reachable from "active" (BFS over the spec's
 * transitions), plus one story that walks as much of the graph as a single
 * continuous interaction can cover. Regenerate with `pnpm generate` after
 * editing the spec — do not edit this file by hand.
 */
function TagStory(props: {  }) {
  const ref = useRef<TagHandle>(null);
  return (
    <Tag
      ref={ref}
      label={"Label content"}
      deleteTrigger={"DeleteTrigger content"}
    />
  );
}

const meta: Meta<typeof TagStory> = {
  title: "Generated/Tag",
  component: TagStory,
};

export default meta;
type Story = StoryObj<typeof TagStory>;

export const Active: Story = {};

// "removed" is reachable per the spec's transition graph but this generator found no click/keyboard/prop path to it automatically.
export const Removed: Story = {};
